### PR TITLE
Add command for close section for commit

### PR DESCRIPTION
**Pull request by bakunyo**
Hello, jreybert.

I want to add a command that can close commit section.
Added key 'CU' means 'commit undo'.

Could you see this PR and merge if the commit is acceptable.

### CODE REVIEW

**Comment by bakunyo** [comment]
Additional comment.
Once open a commit section, it keep on showing without commit done or quit vim.
So I want to close commit section.

**Comment by jreybert** [comment]
Hi bakunyo,

thanks for your PR! I had it in my mind for a while, and I never took the time to add it. You did a good job, too bad that travis is unstable at this moment. I don't see why your commit would fail with the test suite, I think it should be OK. We will see when travis will be back to normal.

Anyway, waiting for travis revival, I would have sevral requests to make this PR complete:
- rebase your commit upon `next` branch
- add this new command `CU` in `README` and `doc/magit.txt`
- the function must do nothing if `b:magit_current_commit_mode == ''`
- when you cancel the commit, could you write the current commit message (using `s:mg_get_commit_msg()`) in the `COMMIT_EDITMSG` file (see `s:mg_get_commit_section()`)

Thanks

**Comment by zimski** [comment]
Hello,
Vimagit act as a regular vim buffer, so i think just pressing (u key) is good enough or maybe i miss something :)

Need to press two times the u key if you start writing the commit

**Comment by bakunyo** [comment]
Hello jreybert,

Thanks for comment!
I have sent another PR https://github.com/jreybert/vimagit/pull/55 , includes some commits referenced your comments.

**Comment by bakunyo** [comment]
Hello zimski,

Thanks for your comment.
It can almost solve closing-commit-section problems!

Though in rare cases, some changes might be staged or unstaged after commit section opened.
Then this 'CU' command looks attractive I think.

**Comment by bakunyo** [comment]
Sorry for sending too PRs.
I wonder which branch(master or next) should be received PR.

Could you close either isn't needed.

**Comment by jreybert** [comment]
@zimski no, just pressing 'u' won't be enough. vimagit is not a nomrla vim buffer. It has some internal variable states. It has one to check that a commit message write is ongoing. Just pressing 'u' won't update this variable.

**Pull request closed without merging**
