### PR TITLE
plugin/magit.vim: suppress more 'line added' messages

### PR DESCRIPTION
**Pull request by joelmo**

### CODE REVIEW

**Comment by jreybert** [comment]
Seems good to me. Don't trust travis integration, it is quite broken these days.

I'll merge this PR soon.

**Comment by jreybert** [comment]
Hi joelmo,

some remarks:
1. your PR does not hurt, it seems fine to me to merge it. Anyway, I would like to understand your current vim setup. Without your commit, I do not notice any 'line added' message. Could you please tell me your vim version, and if you have a partucular vim setting around message verbosity.
2. could you please rebase your commit upon the branch next the repush a pull request?

Thanks for your work!

**Comment by joelmo** [comment]
Thanks. I really like this plugin!

I use this version of vim:
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan 01 1970 00:00:01)
Included patches: 1-826
Compiled by nixbld
Huge version with GTK2 GUI.

Ignore that date, all my binaries have that because I use nix.

I think I saw these messages because I had the setting: set report=0. But anyway I think these puts should be called with silent or maybe temporarily set the setting 'report' to 2 or higher. Because these messages are not useful.

**Comment by jreybert** [comment]
Glad to hear that you like it ☺

  agree that these message are useless, I just would like to be able to reproduce this behavior. I'll try with your setting.

**Pull request merged**
